"""initial schema

Revision ID: 4bb4a052c7c1
Revises: 
Create Date: 2026-09-18 18:10:13.105572
"""
from alembic import op
import sqlalchemy as sa


revision = '4bb4a052c7c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('WHITE_COLLAR', 'BLUE_COLLAR', name='category'), nullable=False),
    sa.Column('workdays', sa.String(length=32), nullable=False),
    sa.Column('weekly_off_days', sa.String(length=32), nullable=False),
    sa.Column('standard_shift_hrs', sa.Float(), nullable=False),
    sa.Column('overtime_allowed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('designations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('WHITE_COLLAR', 'BLUE_COLLAR', name='category'), nullable=False),
    sa.Column('standard_shift_hrs', sa.Float(), nullable=False),
    sa.Column('overtime_applicable', sa.Boolean(), nullable=False),
    sa.Column('allocatable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('public_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_date')
    )
    op.create_table('stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('sequence_order')
    )
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Enum('JUNIOR', 'MID', 'SENIOR', name='skilllevel'), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='employeestatus'), nullable=False),
    sa.Column('ot_eligible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_designation_id'), 'employees', ['designation_id'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_table('stage_designations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id', 'designation_id', name='uq_stage_designation')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('client', sa.String(length=240), nullable=True),
    sa.Column('project_manager_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=240), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='priority'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD', name='projectstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_manager_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_project_code'), 'projects', ['project_code'], unique=True)
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('related_type', sa.Enum('ALLOCATION', 'SHORTAGE', 'CONFLICT', 'RUN_SUMMARY', name='insighttype'), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insight_lookup', 'ai_insights', ['related_type', 'related_id'], unique=False)
    op.create_table('project_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('man_days_budgeted', sa.Integer(), nullable=False),
    sa.Column('stage_start_date', sa.Date(), nullable=True),
    sa.Column('stage_end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'stage_id', name='uq_project_stage')
    )
    op.create_index(op.f('ix_project_stages_project_id'), 'project_stages', ['project_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_stage_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('duration_working_days', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('earliest_start_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('duration_working_days > 0', name='ck_task_duration_positive'),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.ForeignKeyConstraint(['project_stage_id'], ['project_stages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_project_stage_id'), 'tasks', ['project_stage_id'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('actual_start_date', sa.Date(), nullable=False),
    sa.Column('actual_end_date', sa.Date(), nullable=False),
    sa.Column('working_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'DONE', name='allocationstatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_breakdown', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('actual_end_date >= actual_start_date', name='ck_allocation_window'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', name='uq_allocation_task')
    )
    op.create_index('ix_allocation_employee_window', 'allocations', ['employee_id', 'actual_start_date', 'actual_end_date'], unique=False)
    op.create_index(op.f('ix_allocations_employee_id'), 'allocations', ['employee_id'], unique=False)
    op.create_table('shortages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('required_from', sa.Date(), nullable=False),
    sa.Column('required_to', sa.Date(), nullable=False),
    sa.Column('eligible_headcount', sa.Integer(), nullable=False),
    sa.Column('available_headcount', sa.Integer(), nullable=False),
    sa.Column('earliest_available_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['designation_id'], ['designations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortages_project_id'), 'shortages', ['project_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('predecessor_id', sa.Integer(), nullable=False),
    sa.Column('successor_id', sa.Integer(), nullable=False),
    sa.Column('lag_days', sa.Integer(), nullable=False),
    sa.CheckConstraint('predecessor_id != successor_id', name='ck_no_self_dependency'),
    sa.ForeignKeyConstraint(['predecessor_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predecessor_id', 'successor_id', name='uq_task_edge')
    )
    op.create_index(op.f('ix_task_dependencies_predecessor_id'), 'task_dependencies', ['predecessor_id'], unique=False)
    op.create_index(op.f('ix_task_dependencies_successor_id'), 'task_dependencies', ['successor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_dependencies_successor_id'), table_name='task_dependencies')
    op.drop_index(op.f('ix_task_dependencies_predecessor_id'), table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_shortages_project_id'), table_name='shortages')
    op.drop_table('shortages')
    op.drop_index(op.f('ix_allocations_employee_id'), table_name='allocations')
    op.drop_index('ix_allocation_employee_window', table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_tasks_project_stage_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_project_stages_project_id'), table_name='project_stages')
    op.drop_table('project_stages')
    op.drop_index('ix_insight_lookup', table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_index(op.f('ix_projects_project_code'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('stage_designations')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_code'), table_name='employees')
    op.drop_index(op.f('ix_employees_designation_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_table('stages')
    op.drop_table('public_holidays')
    op.drop_table('designations')
    op.drop_table('calendar_rules')
    # ### end Alembic commands ###
